services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app/backend
      - /app/backend/node_modules
    networks:
      - app-networks
  
  frontend:
    build: 
      context: ../frontend
      dockerfile: Dockerfile
      args: 
        API_URL: "http://localhost:80/api"
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - app-networks
    

  webserver:
    depends_on:
      - frontend
      - backend
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: always
    tty: true
    ports:
      - "80:80"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge