services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    networks:
      - app-networks
  
  frontend:
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/app/frontend
      - /app/frontend/node_modules
    networks:
      - app-networks
    args: 
      - API_URL: "http://localhost:3000"

  webserver:
    depends_on:
      - frontend
      - backend
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: always
    tty: true
    ports:
      - "80:80"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge